version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    # Pull the image we have already uploaded from the registry.
    image: mafarrag/getting-started:first-trial
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 400M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet: